name: Deploy to AWS EC2

on:
  push:
    branches:
      - main   # change if you use a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install


      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/ucraft
            git pull origin main
            npm install
            pm2 restart all || pm2 start npm --name "ucraft" -- start
